version: 2

models:
  - name: silver_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: order_status
        tests:
          - accepted_values:
              values: ['delivered','shipped','canceled',
                       'unavailable','invoiced','processing',
                       'approved','created']

  - name: silver_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: silver_payments
    columns:
      - name: order_id
        tests:
          - not_null
      - name: payment_type
        tests:
          - accepted_values:
              values: ['credit_card','boleto','voucher',
                       'debit_card','not_defined']

  - name: silver_sellers
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null